### PR TITLE
Update dependencies to comply with upcoming (Apple) Privacy Manifest requirements

### LINKED ISSUE #160: package_info_plus: ^5.0.1
please update to package_info_plus: ^5.0.1

### PR DESCRIPTION
**Pull request by jamieastley**
- Bumped major versions of following dependencies:

  - `sensors_plus:` `^3.0.2` -> `^5.0.0`
  - `share_plus:` `^7.0.2` -> `^8.0.2`
  - `package_info_plus:` `^4.0.2` -> `^6.0.0`
  - `flutter_local_notifications:` `^16.1.0` -> `^17.0.0`

This is required to include the privacy manifests added to the above plugins as mentioned in https://github.com/fluttercommunity/plus_plugins/issues/2447 by 1st May 2024.

- Migrate from [deprecated imperative Gradle plugin to declarative approach](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply#validation) in `example`

Tested and confirmed above changes on both Android and iOS.

Fixes #160.

### CODE REVIEW

**Comment by jamieastley** [comment]
Apologies for the direct mention @jhomlala, but given the hard requirement to support Privacy Manifest requirements by 1st May, it would be greatly appreciated to publish a new package update to pub.dev with the above updates to unblock consumers from updating dependencies and testing their compliance prior to this deadline to avoid submission rejections.

**Comment by takla21** [comment]
Any news on this?

**Comment by Soap-141** [comment]
Hello?

**Comment by CBodnarHorvath** [comment]
Would be great if this could get unblocked

**Comment by jhomlala** [comment]
Thanks, merged!

**Comment by jamieastley** [comment]
As a heads up to anyone who might have pointed to my forked branch - I'll leave it up for a little while but will be deleting it soon after the update is published to pub.dev.

**Pull request merged**
