### PR TITLE
Feat/translation

### PR DESCRIPTION
**Pull request by jhomlala**
Changelog:
* Added AliceTranslations class which acts as translation registry. We can't use localization delegate because we're not using MaterialApp widget.
* Added `context.i18n` extension to access translations
* Added tests

### CODE REVIEW

**Comment by jhomlala** [comment]
@techouse Could you check it please?

**Comment by techouse** [comment]
Looks good at first glance, I just wonder why you didn't opt for something like https://pub.dev/packages/easy_localization and JSON files.

**Comment by jhomlala** [comment]
I'm trying to not using deps which I can easily handle. Less deps = more maintainable code. Also `easy_localizatio`n requires using assets which could be hard in package.

**Comment by techouse** [comment]
LGTM then :)

**Review by techouse — APPROVED** [review]

**Pull request merged**
