### PR TITLE
chore: clean up examples/alice_http_client

### PR DESCRIPTION
**Pull request by techouse**
- [x] drop web example
- [x] drop windows example
- [x] drop linux example 
- [x] drop macos example

---

This PR re-applies the changes made in https://github.com/jhomlala/alice/commit/29a71dba97c7a4cabc24ab758c608fb720652687 as a PR

### CODE REVIEW

**Comment by jhomlala** [comment]
I'm back with question:

Why we're dropping support for desktop? The goal is to have support for all platforms, except web where it's easy to use build in inspector.

**Comment by jhomlala** [comment]
Sure, but let's imagine scenario where you're manual tester and you don't have an access to the code and want to share information about calls from some desktop application which you're testing.

**Comment by techouse** [comment]
Besides, 
image

**Comment by jhomlala** [comment]
Yeah I know, it's because of the dependencies that we're using - pub.dev analyzer (pana) is really restrictive. Anyway at this moment we know that Alice works fine on mobile, but ultimate goal is to support other platforms too. Web doesn't make any sense - there are build in inspector tools in web browsers. But for desktop, we could have support without doing huge changes.
At this moment it's okay to remove unsupported platforms from examples, but at the end we will revert it in some point in the future.

**Review by jhomlala — APPROVED** [review]

**Comment by techouse** [comment]
Ok, if that's the ultimate goal, then we add them back in the examples in the future.

**Pull request merged**
