### PR TITLE
RxDart Version Update

### PR DESCRIPTION
**Pull request by gagan-garcha**

### CODE REVIEW

**Comment by TramPamPam** [comment]
Hi @jhomlala 

Any update on this?

**Comment by julianfalcionelli** [comment]
Can we move forward with this please?

**Comment by alyyasser** [comment]
i got some lint warning with the latest version of rxdart (0.27.1), would be nice to fix them too.
image

also, would you bump `permission_handler` to the latest version too? that would fix this issue: #83

**Comment by jhomlala** [comment]
Fixed dependencies versions with my other commit. Closing this PR.

**Comment by jhomlala** [comment]
@gagan-garcha @TramPamPam @julianfalcionelli @alyyasser Please upgrade your Alice version to 0.2.2.

**Pull request closed without merging**
