### PR TITLE
fix: alice_chopper interceptor

### PR DESCRIPTION
**Pull request by techouse**
This PR supersedes #180

---

Hey 👋

Recently I stumbled upon this awesome package and I noticed it (also) uses [Chopper](https://pub.dev/packages/chopper) [Interceptors](https://hadrien-lejard.gitbook.io/chopper/interceptors).

In [Chopper v8.0.0](https://pub.dev/packages/chopper/changelog#800), there was a significant [restructuring of interceptors](https://github.com/lejard-h/chopper/pull/547). The `RequestInterceptor` and `ResponseInterceptor` classes, as well as their function counterparts, were removed.

Since I'm one of the [maintainers of Chopper](https://github.com/lejard-h/chopper?tab=readme-ov-file#contributors-) I thought I'd contribute to this library by updating the `AliceChopperInterceptor` to be compatible with Chopper v8.0.0.

CC / @Guldem

---

✅ I tested the provided Alice Chopper example on an Android Simulator.

### CODE REVIEW

**Comment by techouse** [comment]
Can you please throw an eye on this once you can @jhomlala 🙏

CC / @Guldem

**Review by Guldem — APPROVED** [review]
LGTM!

Expect I still have the same questions about the `alice_token` headers thats added when making the hashcode of the request. 

Also I'm still wondering if the hashcode is needed at all.

**Comment by techouse** [comment]
> Expect I still have the same questions about the alice_token headers thats added when making the hashcode of the request.

Yeah, I kept it in because I'm not 100% sure it can be dropped. @jhomlala can probably shed some light on it.

**Comment by Guldem** [comment]
> > Expect I still have the same questions about the alice_token headers thats added when making the hashcode of the request.
> 
> Yeah, I kept it in because I'm not 100% sure it can be dropped. @jhomlala can probably shed some light on it.

Just reminding every one ^^

**Comment by jhomlala** [comment]
I think alice token can be removed - it's deprecated. I'll merge this PR and fix it with another PR. Thanks!

**Pull request merged**
