### PR TITLE
chore: refactor `AliceChopperAdapter`

### PR DESCRIPTION
**Pull request by techouse**
This PR refactors the Alice Chopper interceptor even further by:
- ~~removing the [deprecated](https://github.com/jhomlala/alice/pull/185#issuecomment-2155322912) `alice_token`~~ turns out, `alice_token` is required to keep track of calls & responses
  - I opted into using `UUIDv4` as the `alice_token` since it offers true uniqueness. In case this is not desired I can reverse back to microseconds. Note that milliseconds are **NOT** unique enough.
- obtaining the `body` size in a safer way
- getting rid of all unnecessary intermediary variables
- updates the Alice Chopper example

### CODE REVIEW

**Comment by jhomlala** [comment]
Hey, thanks for this refactor. When I run your adapter with alice_chopper example, it shows me this error. I think this is something with `getRequestHashCode`. Can you check it please?
```dart
I/flutter ( 9961): Bad state: No element
I/flutter ( 9961): #0      Iterable.reduce (dart:core/iterable.dart:375:7)
I/flutter ( 9961): #1      AliceChopperAdapter.getRequestHashCode (package:alice_chopper/alice_chopper_adapter.dart:21:14)
I/flutter ( 9961): #2      AliceChopperAdapter.intercept (package:alice_chopper/alice_chopper_adapter.dart:37:23)
I/flutter ( 9961): <asynchronous suspension>
I/flutter ( 9961): #3      InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46:16)
I/flutter ( 9961): <asynchronous suspension>
I/flutter ( 9961): #4      RequestConverterInterceptor.intercept (package:chopper/src/interceptors/request_converter_interceptor.dart:26:7)
I/flutter ( 9961): <asynchronous suspension>
I/flutter ( 9961): #5      InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46:16)
I/flutter ( 9961): <asynchronous suspension>
I/flutter ( 9961): #6      Call.execute (package:chopper/src/chain/call.dart:56:12)
I/flutter ( 9961): <asynchronous suspension>
I/flutter ( 9961): #7      ChopperClient.send (package:chopper/src/base.dart:175:22)
I/flutter ( 9961): <asynchronous suspension>
```

**Comment by techouse** [comment]
Oops ... lemme check 🙈

**Comment by jhomlala** [comment]
Maybe I was wrong and `alice_token` is required :)

**Comment by techouse** [comment]
Fixed. Since `alice_token` was always there map + reduce worked, but if it's empty this will throw an error. So I used `fold` with a default of `0`.

**Comment by jhomlala** [comment]
Amazing! It's not crashing anymore. But when I look into inspector, it looks like responses are not added into call.

image
image

Could you please verify why it's happening?  Also I see that Alice should have some unit tests. This is something for next PRs.

**Comment by techouse** [comment]
I fixed it. Can you please check it again?

**Comment by jhomlala** [comment]
image
Great! Some requests are still loading forever. Could you look again at it when you have some time? 👀

**Comment by techouse** [comment]
Working on it. I pushed an update that fixed it, but has some analysis issues. I'll check again in the evening.

**Comment by jhomlala** [comment]
No worries, take your time. Thanks!

**Comment by techouse** [comment]
@jhomlala right, this should work as expected. I've updated the example quite a bit, so it covers a lot.

**Comment by jhomlala** [comment]
@techouse Thanks for this amazing work! Yes, I think this UUID package is fine. Overall it's LGTM. Are you planning to add more refactors or are we ready to merge it?

**Review by jhomlala — APPROVED** [review]

**Comment by techouse** [comment]
> Are you planning to add more refactors or are we ready to merge it?

Nope. That's all she wrote.

**Comment by jhomlala** [comment]
Included in 1.0.3 version of alice_chopper.

**Pull request merged**
